# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mx189n2fK3fbmoZrbHMbZqU8lfsCkiQ7
"""

responses = {
    "hello": "Hi there!",
    "hi": "Hey! 👋",
    "hey": "Hello!",
    "how are you": "I'm just a bot, but I'm doing great! 😊",
    "what's your name": "I'm your friendly chatbot!",
    "who made you": "I was created by Miral 😎",
    "bye": "Goodbye! Talk to you later 👋",
    "thank you": "You're welcome! 😊",
    "help": "You can say things like 'hello', 'how are you', or 'bye'.",
    "what can you do": "I can chat with you and keep you company 🤖",
    "tell me a joke": "Why did the computer go to therapy? Because it had too many bytes of emotional baggage 😆",
    "date": "I'm always here for you, but I can't go on a date with you 😅",
    "i'm bored": "Let's play a game! Just kidding, I'm not that smart yet 😜",
    "you are smart": "Thank you! I try my best 🧠",
    "you are funny": "Haha you're making me blush 🤖❤️",
}


print("🤖 Chatbot: Hello! Type something to begin. Type 'exit' to end.")

while True:
    user_input = input("🧑 You: ").lower().strip()

    if user_input == "exit":
        print("🤖 Chatbot: Bye! Have a great day.")
        break

    response = responses.get(user_input, "I don't understand that.")
    print(f"🤖 Chatbot: {response}")